"""
Exports all users from the SQLite database as a JS file (users_db.js)
that the browser can use for offline authentication.
Run this script whenever users are added/changed.
"""
import sqlite3, json, os, sys

DB_PATH  = os.path.join(os.path.dirname(__file__), 'instance', 'network.db')
OUT_PATH = os.path.join(os.path.dirname(__file__), 'static', 'js', 'users_db.js')

if not os.path.exists(DB_PATH):
    print(f'ERROR: database not found at {DB_PATH}')
    sys.exit(1)

conn = sqlite3.connect(DB_PATH)
conn.row_factory = sqlite3.Row
c = conn.cursor()

c.execute("""
    SELECT id, name, email, password, bio, interests, skills,
           location, avatar_color, profile_pic
    FROM user ORDER BY id
""")
rows = c.fetchall()

users = []
for r in rows:
    users.append({
        'id':           r['id'],
        'name':         r['name'],
        'email':        r['email'].strip().lower(),
        'password':     r['password'],          # Werkzeug pbkdf2 hash
        'bio':          r['bio']          or '',
        'interests':    r['interests']    or '',
        'skills':       r['skills']       or '',
        'location':     r['location']     or '',
        'avatar_color': r['avatar_color'] or '#3b82f6',
        'profile_pic':  r['profile_pic']  or '',
    })

conn.close()

js_content = f"""/* AUTO-GENERATED by export_users.py — do not edit manually */
/* Re-run export_users.py after adding / changing users.      */
window.DB_USERS = {json.dumps(users, indent=2, ensure_ascii=False)};
"""

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f'Exported {len(users)} users -> {OUT_PATH}')
for u in users:
    print(f"  #{u['id']:3d} {u['name']:<30s} {u['email']}")
